apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Include all your microservices
resources:
- APP
- WEB
- MC
- DB
- RMQ
- Storage

# 2. Define the Images to Automate
# The Updater will look for these 'name' fields and update 'newTag'
images:
- name: java-app-image
  newName: 079815393835.dkr.ecr.us-east-1.amazonaws.com/app
  newTag: 679f78d
