apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-namespace.yaml
  - db-secret.yaml
  - db-config-query.yaml
  - db-Statefulset.yaml
  - db-service.yaml
  - db-networkpolicy.yaml
