name: Build app and Docker img for Tomcat

on:
  push:
    branches:
      - Ci-Branch
    paths:
      - "sourcecodeseniorwr/**"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build WAR, Scan & Push Immutable Docker Image

    defaults:
      run:
        working-directory: sourcecodeseniorwr

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Validate Maven config
        run: mvn -B validate --no-transfer-progress

      - name: Build WAR package
        run: mvn -B clean package --no-transfer-progress

      - name: Run tests
        run: mvn -B test --no-transfer-progress

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: tomcat-war-package
          path: sourcecodeseniorwr/target/*.war

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: sourcecodeseniorwr/target
          severity: CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Build Docker Image
        working-directory: ${{ github.workspace }}
        run: docker build -t tomcat-app -f Dockerfile .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag (Immutable)
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Tag Docker Image
        run: docker tag tomcat-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/app:${{ env.IMAGE_TAG }}

      - name: Push Docker Image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/app:${{ env.IMAGE_TAG }}
