name: "Terraform EKS Pipeline"

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Terrafrom

    steps:
      # 1. Get the code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Login to AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      # 4. Connect to S3 Backend and download plugins
      - name: Terraform Init
        id: init
        run: terraform init

      # 5. Check for errors
      - name: Terraform Validate
        id: validate
        run: terraform validate

      # 8. Apply Changes (Manual Trigger)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
